# Generated by Django 3.2.4 on 2023-04-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('statuscategorychangedate', 'Statuscategorychangedate'), ('issuetype', 'Issuetype'), ('timespent', 'Timespent'), ('project', 'Project'), ('fixVersions', 'Fixversions'), ('aggregatetimespent', 'Aggregatetimespent'), ('resolution', 'Resolution'), ('resolutiondate', 'Resolutiondate'), ('workratio', 'Workratio'), ('lastViewed', 'Lastviewed'), ('watches', 'Watches'), ('created', 'Created'), ('priority', 'Priority'), ('timeestimate', 'Timeestimate'), ('issuelinks', 'Issuelinks'), ('description', 'Description'), ('security', 'Security'), ('summary', 'Summary'), ('progress', 'Progress'), ('show_custom', 'Show Custom')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=500)),
                ('jira_issue_types', models.ManyToManyField(blank=True, to='testy_jira.JiraIssueType')),
            ],
        ),
    ]
