# Generated by Django 3.2.4 on 2023-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy_jira', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='jira_issue_types',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='selected_issue_keys',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='JiraIssueType',
        ),
    ]
