# Generated by Django 3.2.4 on 2023-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy_jira', '0002_auto_20230420_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('info', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
