# Generated by Django 3.2.4 on 2023-04-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testy_jira', '0003_jiraissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='requesting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testy_jira.userinfo'),
        ),
    ]
